import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /// The rasteriser sets type from `.fonts/` (generated by
  /// `mirror-excalidraw-assets.mts`), which is outside `public/` because
  /// `public/` is not on a Vercel function's filesystem. Traced into the two
  /// routes that render pictures for a model — about 700 KB of classic TTFs.
  outputFileTracingIncludes: {
    "/api/trpc/*": [".fonts/**/*"],
    "/api/agents/vibes/worker": [".fonts/**/*"],
  },
  /// resvg is a native addon and its `.node` binding is not a bundleable
  /// asset — loaded from node_modules at runtime instead, the way sharp
  /// already is by Next's own default list.
  serverExternalPackages: ["@resvg/resvg-js"],
};

export default nextConfig;
