import type { AnalysisView } from "@/lib/analysis/analysis-view";
import { isGeneratedReference } from "@/lib/references/reference-filter";
import { AnalysisBadge } from "../../../_reference/components/analysis-badge";
import type { GalleryTileReference } from "../types";

export function GalleryTile({
  reference,
  analysis,
  crops,
  onOpen,
  onToggleFavorite,
  onOpenProperties,
  remove,
}: {
  reference: GalleryTileReference;
  analysis: AnalysisView | null;
  crops: string | null;
  onOpen: () => void;
  onToggleFavorite: () => void;
  onOpenProperties: () => void;
  remove: React.ReactNode;
}) {
  return (
    <li className="flex flex-col overflow-hidden rounded-xl border border-current/10">
      <div className="relative aspect-[4/3] bg-current/5">
        <button
          type="button"
          onClick={onOpen}
          aria-label={`Open ${reference.title || "reference"} full size`}
          className="block h-full w-full cursor-zoom-in"
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={reference.thumbUrl}
            alt={reference.title}
            loading="lazy"
            className="h-full w-full object-cover"
          />
        </button>

        <button
          type="button"
          onClick={onToggleFavorite}
          aria-pressed={reference.isFavorite}
          aria-label={reference.isFavorite ? "Remove from favorites" : "Add to favorites"}
          className="absolute top-2 right-2 rounded-full bg-[var(--background)]/85 px-2 py-1 text-sm leading-none"
        >
          {reference.isFavorite ? "★" : "☆"}
        </button>
      </div>

      <div className="flex flex-1 flex-col gap-1 px-3 py-2 text-xs">
        {reference.title ? <span className="font-medium">{reference.title}</span> : null}
        <div className="mt-auto flex flex-wrap items-center justify-between gap-2 pt-1">
          <div className="flex min-w-0 items-center gap-1.5">
            {analysis ? <AnalysisBadge view={analysis} /> : null}
            {isGeneratedReference(reference) ? (
              <span
                title={reference.generationPrompt ?? "Generated by the assistant"}
                className="shrink-0 rounded-full border border-current/25 px-1.5 py-0.5 text-[10px] opacity-70"
              >
                Generated
              </span>
            ) : null}
            {crops ? (
              <button
                type="button"
                onClick={onOpenProperties}
                title={`${crops} of this reference — open its properties`}
                aria-label={`${crops} of ${reference.title || "reference"} — open its properties`}
                className="shrink-0 rounded-full border border-current/25 px-1.5 py-0.5 text-[10px] opacity-70 hover:opacity-100"
              >
                {crops}
              </button>
            ) : null}
          </div>
          {remove}
        </div>
      </div>
    </li>
  );
}
